config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :movie, optional: true
  validates :name, presence: true
  validates :age, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :clients, dependent: :nullify
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.includes(:movie).all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:movie_id, :name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movies_url, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <% if controller.action_name == 'index' %>
    <tr>
      <th scope="row"><%= client.id %></th>
      <td><%= client.name %></td>
      <td><%= client.age %></td>
      <td><%= client.movie ? client.movie.title : "Sin película" %></td>
        <td><%= link_to "Mostrar Cliente", client, class: 'btn btn-primary' %></td>
    </tr>
  <% else %>
    <div class="card text-bg-light mb-3 mt-5">
      <h1 class="card-header text-center"><%= client.name %></h1>
      <div class="card-body">
        <p class="card-text"><b>Edad: </b><%= client.age %></p>
        <p class="card-text"><b>Película: </b><%= client.movie ? client.movie.title : "Sin película" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class:"form-label mt-3" %>
    <%= form.text_field :name, class:"form-control", required: true %>
  </div>

  <div>
    <%= form.label :age, style: "display: block", class:"form-label mt-3" %>
    <%= form.text_field :age, class:"form-control", required: true %>
  </div>

  <div>
    <%= form.label :movie_id, style: "display: block", class:"form-label mt-3" %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title, {}, { class: "form-select", required: true } %>
  </div>

  <div class="mt-3">
    <div class="d-flex justify-content-center">
      <%= link_to "<", clients_path, class: 'btn btn-outline-primary m-2' %>
      <% if action_name == 'edit' %>
        <%= link_to "Mostrar Cliente", @client, class: 'btn btn-outline-primary m-2' %>
      <% end %>
      <%= form.submit class: "btn btn-primary m-2" %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <h1 class='text-center mt-5'>Editar cliente</h1>

    <%= render "form", client: @client %>


  </div>
</div>

app/views/clients/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container">
  <h1 class='text-center mt-5'>Clientes</h1>

  <%= link_to "Nuevo cliente", new_client_path, class: 'btn btn-primary my-4' %>

  <div id="clients">
    <table class="table table-striped table-hover">
      <thead  class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Edad</th>
          <th scope="col">Película</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @clients.each do |client| %>
          <%= render client %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <h1 class='text-center mt-5'>Nuevo cliente</h1>

    <%= render "form", client: @client %>

    <br>
  </div>
</div>

app/views/clients/show.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <%= render @client %>

    <div class="d-flex justify-content-center">
      <%= link_to "<", clients_path, class: 'btn btn-outline-primary m-2' %>
      <%= link_to "Editar Cliente", edit_client_path(@client), class: 'btn btn-outline-primary m-2' %>
      <%= button_to "Eliminar Cliente", @client, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger m-2' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Título", style: "display: block", class:"form-label mt-3", required: true %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mt-3">
    <div class="d-flex justify-content-center">
      <%= link_to "<", movies_path, class: 'btn btn-outline-primary m-2' %>
      <% if action_name == 'edit' %>
        <%= link_to "Mostrar Película", @movie, class: 'btn btn-outline-primary m-2' %>
      <% end %>
      <%= form.submit (action_name == 'edit' ? 'Editar Película' : 'Crear Película'), class: "btn btn-primary m-2" %>
    </div>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% if controller.controller_name == 'movies' && controller.action_name == 'index' %>
  <div class="col-md-4 py-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
        <%= link_to "Mostrar Película", movie, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% elsif controller.controller_name == 'movies' && controller.action_name == 'show' %>
  <div class="col-md-12 py-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <h1 class='text-center mt-5'>Editar pelicula</h1>

    <%= render "form", movie: @movie %>

    <br>
  </div>
</div>

app/views/movies/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container">
  <h1 class='text-center mt-5'>Películas</h1>
  <%= link_to "Nueva Película", new_movie_path, class: 'btn btn-primary my-4' %>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <h1 class='text-center mt-5'>Nuevo película</h1>

    <%= render "form", movie: @movie %>

    <br>
  </div>
</div>

app/views/movies/show.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-6 py-2">
    <p style="color: green"><%= notice %></p>

    <%= render @movie %>


    <div class="d-flex justify-content-center">
      <%= link_to "<", movies_path, class: 'btn btn-outline-primary m-2' %>
      <%= link_to "Editar Pelicula", edit_movie_path(@movie), class: 'btn btn-outline-primary m-2' %>
      <%= button_to "Eliminar Película", @movie, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger m-2' %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" id="menu">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', alt: 'BlockBuster Logo', width: '210' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to 'Clientes', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Películas', movies_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>